version: "3.8"

services:
  db:
    image: postgres:16-alpine3.23
    container_name: book_reviews_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: superman
      POSTGRES_DB: book_reviews
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
